// Code generated by "stringer -type=Special"; DO NOT EDIT.

package input

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Text-0]
	_ = x[Enter-1]
	_ = x[Tab-2]
	_ = x[Backtab-3]
	_ = x[Backspace-4]
	_ = x[Esc-5]
	_ = x[CursorMove-6]
	_ = x[FocusIn-7]
	_ = x[FocusOut-8]
}

const _Special_name = "TextEnterTabBacktabBackspaceEscCursorMoveFocusInFocusOut"

var _Special_index = [...]uint8{0, 4, 9, 12, 19, 28, 31, 41, 48, 56}

func (i Special) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Special_index)-1 {
		return "Special(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Special_name[_Special_index[idx]:_Special_index[idx+1]]
}
