// Code generated by "stringer -type=mouseEventType -trimprefix=mouseEventType"; DO NOT EDIT.

package editor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[mouseEventTypeRaw-0]
	_ = x[mouseEventTypeClick-1]
	_ = x[mouseEventTypeDoubleClick-2]
	_ = x[mouseEventTypeTripleClick-3]
	_ = x[mouseEventTypeDragStart-4]
	_ = x[mouseEventTypeDragEnd-5]
	_ = x[mouseEventTypeScroll-6]
}

const _mouseEventType_name = "RawClickDoubleClickTripleClickDragStartDragEndScroll"

var _mouseEventType_index = [...]uint8{0, 3, 8, 19, 30, 39, 46, 52}

func (i mouseEventType) String() string {
	if i >= mouseEventType(len(_mouseEventType_index)-1) {
		return "mouseEventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _mouseEventType_name[_mouseEventType_index[i]:_mouseEventType_index[i+1]]
}
