// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package editor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TtNothing-0]
	_ = x[TtKeyword-1]
	_ = x[TtIdentifier-2]
	_ = x[TtTypeRef-3]
	_ = x[TtImportRef-4]
	_ = x[TtFuncDeclaration-5]
	_ = x[TtCall-6]
	_ = x[TtStringLiteral-7]
	_ = x[TtNumberLiteral-8]
	_ = x[TtComment-9]
}

const _TokenType_name = "TtNothingTtKeywordTtIdentifierTtTypeRefTtImportRefTtFuncDeclarationTtCallTtStringLiteralTtNumberLiteralTtComment"

var _TokenType_index = [...]uint8{0, 9, 18, 30, 39, 50, 67, 73, 88, 103, 112}

func (i TokenType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TokenType_index)-1 {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[idx]:_TokenType_index[idx+1]]
}
