// Command fetchcore copies the Go bindings of tree-sitter with a newer core
// library than the one they ship with. It's meant to be run by go generate in
// the package holding the copy:
//
//	//go:generate go run ./fetchcore <bindings revision> <core revision>
//
// The Go files, the allocator, and the license come from go-tree-sitter at the
// bindings revision, and the C sources and headers under src and include come
// from tree-sitter at the core revision. A revision is a tag or a commit.
// The revisions are recorded in upstream.go.
package main

import (
	"bytes"
	"fmt"
	"io/fs"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	bindingsRepo = "https://github.com/tree-sitter/go-tree-sitter"
	coreRepo     = "https://github.com/tree-sitter/tree-sitter"
)

func main() {
	log.SetFlags(0)
	log.SetPrefix("fetchcore: ")
	if len(os.Args) != 3 {
		log.Fatal("usage: fetchcore <bindings revision> <core revision>")
	}
	pkg := os.Getenv("GOPACKAGE")
	if pkg == "" {
		log.Fatal("GOPACKAGE is not set: run it with go generate")
	}
	if err := fetch(os.Args[1], os.Args[2], ".", pkg); err != nil {
		log.Fatal(err)
	}
	log.Printf("copied %s@%s with %s@%s", bindingsRepo, os.Args[1], coreRepo, os.Args[2])
}

// ownFiles are the files of the package that are not copied from upstream.
var ownFiles = map[string]bool{"doc.go": true}

// fetch copies the bindings and the core into dir, which holds the Go package pkg.
func fetch(bindingsRev, coreRev, dir, pkg string) error {
	tmp, err := os.MkdirTemp("", "fetchcore-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmp)

	bindings, core := filepath.Join(tmp, "bindings"), filepath.Join(tmp, "core")
	if err := clone(bindingsRepo, bindingsRev, bindings); err != nil {
		return err
	}
	if err := clone(coreRepo, coreRev, core); err != nil {
		return err
	}

	// Collect everything before touching dir: a repository lacking a file must
	// leave the current copy intact.
	files := make(map[string][]byte)
	entries, err := os.ReadDir(bindings)
	if err != nil {
		return err
	}
	for _, e := range entries {
		name := e.Name()
		copied := (strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go")) ||
			name == "allocator.c" || name == "allocator.h" || name == "LICENSE"
		if !copied || e.IsDir() || ownFiles[name] {
			continue
		}
		if files[name], err = os.ReadFile(filepath.Join(bindings, name)); err != nil {
			return err
		}
	}
	for _, sub := range []string{"src", "include"} {
		root := filepath.Join(core, "lib", sub)
		err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
			if err != nil || d.IsDir() {
				return err
			}
			rel, err := filepath.Rel(root, path)
			if err != nil {
				return err
			}
			files[sub+"/"+filepath.ToSlash(rel)], err = os.ReadFile(path)
			return err
		})
		if err != nil {
			return err
		}
	}
	files["upstream.go"] = upstreamSource(pkg, bindingsRev, coreRev)

	// Files dropped upstream must not linger.
	for _, sub := range []string{"src", "include"} {
		if err := os.RemoveAll(filepath.Join(dir, sub)); err != nil {
			return err
		}
	}
	current, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, e := range current {
		if !e.IsDir() && !ownFiles[e.Name()] {
			if err := os.Remove(filepath.Join(dir, e.Name())); err != nil {
				return err
			}
		}
	}
	for name, data := range files {
		path := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, data, 0o644); err != nil {
			return err
		}
	}
	return nil
}

func upstreamSource(pkg, bindingsRev, coreRev string) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by fetchcore; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "// The repositories and the revisions the sources are copied from: the Go files\n")
	fmt.Fprintf(&b, "// from UpstreamBindings, and the C sources under src and include from UpstreamCore.\n")
	fmt.Fprintf(&b, "const (\n\tUpstreamBindings = %q\n\tUpstreamCore     = %q\n)\n",
		bindingsRepo+"@"+bindingsRev, coreRepo+"@"+coreRev)
	return b.Bytes()
}

// clone checks out the tag or the commit of the repository into dst.
func clone(repo, rev, dst string) error {
	for _, args := range [][]string{
		{"init", "--quiet", dst},
		{"-C", dst, "fetch", "--quiet", "--depth=1", repo, rev},
		{"-C", dst, "checkout", "--quiet", "FETCH_HEAD"},
	} {
		cmd := exec.Command("git", args...)
		var stderr bytes.Buffer
		cmd.Stderr = &stderr
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("git %s: %w: %s", strings.Join(args, " "), err, bytes.TrimSpace(stderr.Bytes()))
		}
	}
	return nil
}
