// Code generated by "stringer -type=Cursor -trimprefix=Cursor"; DO NOT EDIT.

package inputs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CursorArrowUp-0]
	_ = x[CursorArrowDown-1]
	_ = x[CursorArrowLeft-2]
	_ = x[CursorArrowRight-3]
	_ = x[CursorHome-4]
	_ = x[CursorEnd-5]
}

const _Cursor_name = "ArrowUpArrowDownArrowLeftArrowRightHomeEnd"

var _Cursor_index = [...]uint8{0, 7, 16, 25, 35, 39, 42}

func (i Cursor) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Cursor_index)-1 {
		return "Cursor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Cursor_name[_Cursor_index[idx]:_Cursor_index[idx+1]]
}
