// Command fetchgrammar copies the C sources of a tree-sitter grammar from its
// git repository into the current directory, for grammars that have no Go
// bindings upstream. It's meant to be run by go generate in the package that
// provides the bindings:
//
//	//go:generate go run ../fetchgrammar https://github.com/owner/tree-sitter-lang main
//
// The branch is cloned into a temporary directory, and the parser, the external
// scanner, the tree-sitter headers and the license replace the ones in the
// current directory. The commit they come from is recorded in upstream.go.
package main

import (
	"bytes"
	"fmt"
	"io/fs"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

func main() {
	log.SetFlags(0)
	log.SetPrefix("fetchgrammar: ")
	if len(os.Args) != 3 {
		log.Fatal("usage: fetchgrammar <repository URL> <branch>")
	}
	pkg := os.Getenv("GOPACKAGE")
	if pkg == "" {
		log.Fatal("GOPACKAGE is not set: run it with go generate")
	}
	commit, err := fetch(os.Args[1], os.Args[2], ".", pkg)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("copied %s at %s", os.Args[1], commit)
}

// grammarFiles are the files copied from the repository, relative to its root.
// The headers under src/tree_sitter are copied as well.
var grammarFiles = []string{"src/parser.c", "src/scanner.c", "LICENSE"}

// fetch copies the grammar from the branch of the repository into dir, which
// holds the Go package pkg, and returns the commit it's copied from.
func fetch(repo, branch, dir, pkg string) (string, error) {
	tmp, err := os.MkdirTemp("", "fetchgrammar-")
	if err != nil {
		return "", err
	}
	defer os.RemoveAll(tmp)

	clone := filepath.Join(tmp, "repo")
	if _, err := git(tmp, "clone", "--quiet", "--depth=1", "--branch="+branch, repo, clone); err != nil {
		return "", err
	}
	commit, err := git(clone, "rev-parse", "HEAD")
	if err != nil {
		return "", err
	}

	// Collect everything before touching dir: a repository lacking a file must
	// leave the current copy intact.
	files := make(map[string][]byte)
	for _, name := range grammarFiles {
		data, err := os.ReadFile(filepath.Join(clone, name))
		if err != nil {
			return "", err
		}
		files[name] = data
	}
	headers, err := filepath.Glob(filepath.Join(clone, "src", "tree_sitter", "*.h"))
	if err != nil {
		return "", err
	}
	if len(headers) == 0 {
		return "", fmt.Errorf("no headers in src/tree_sitter of %s", repo)
	}
	for _, path := range headers {
		data, err := os.ReadFile(path)
		if err != nil {
			return "", err
		}
		files["src/tree_sitter/"+filepath.Base(path)] = data
	}
	files["upstream.go"] = upstreamSource(pkg, repo, branch, commit)

	// Files dropped upstream must not linger.
	if err := os.RemoveAll(filepath.Join(dir, "src")); err != nil {
		return "", err
	}
	for name, data := range files {
		path := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return "", err
		}
		if err := os.WriteFile(path, data, fs.FileMode(0o644)); err != nil {
			return "", err
		}
	}
	return commit, nil
}

func upstreamSource(pkg, repo, branch, commit string) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by fetchgrammar; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "// Upstream is the repository and the commit the sources under src are copied\n")
	fmt.Fprintf(&b, "// from, taken from its %s branch.\n", branch)
	fmt.Fprintf(&b, "const Upstream = %q\n", repo+"@"+commit)
	return b.Bytes()
}

func git(dir string, args ...string) (string, error) {
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("git %s: %w: %s", strings.Join(args, " "), err, bytes.TrimSpace(stderr.Bytes()))
	}
	return strings.TrimSpace(string(out)), nil
}
