// Code generated by fetchcore; DO NOT EDIT.

package tree_sitter

// The repositories and the revisions the sources are copied from: the Go files
// from UpstreamBindings, and the C sources under src and include from UpstreamCore.
const (
	UpstreamBindings = "https://github.com/tree-sitter/go-tree-sitter@adc13ffd8b2c0b01b878fda9f7c422ce0df5fad3"
	UpstreamCore     = "https://github.com/tree-sitter/tree-sitter@v0.25.10"
)
